import { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export type Language = 'pl' | 'en' | 'tr';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

interface LanguageProviderProps {
  children: ReactNode;
}

export const LanguageProvider = ({ children }: LanguageProviderProps) => {
  const [language, setLanguage] = useState<Language>('pl'); // Default to Polish

  useEffect(() => {
    // Load language from localStorage or default to Polish
    const savedLanguage = localStorage.getItem('language') as Language;
    if (savedLanguage && ['pl', 'en', 'tr'].includes(savedLanguage)) {
      setLanguage(savedLanguage);
    }
  }, []);

  const handleLanguageChange = (lang: Language) => {
    setLanguage(lang);
    localStorage.setItem('language', lang);
  };

  const t = (key: string): string => {
    return translations[language]?.[key] || translations['pl'][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleLanguageChange, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

// Translation object
const translations: Record<Language, Record<string, string>> = {
  pl: {
    // Navigation
    'nav.home': 'Strona Główna',
    'nav.courses': 'Kursy',
    'nav.gallery': 'Galeria',
    'nav.instructors': 'Instruktorzy',
    'nav.students': 'Studenci',
    'nav.success': 'Sukcesy',
    'nav.blog': 'Blog',
    'nav.contact': 'Kontakt',
    'nav.enroll': 'Zapisz się',

    // Hero Section
    'hero.title': 'K&K Akademia Fryzjerska',
    'hero.subtitle': 'Rozwijaj swoje umiejętności fryzjerskie z najlepszymi instruktorami w Warszawie',
    'hero.description': 'Dołącz do naszej profesjonalnej akademii i przekształć swoją pasję w dochodową karierę. Kompleksowe szkolenia, praktyczne doświadczenie i wsparcie w karierze.',
    'hero.cta.primary': 'Zapisz się na Kurs',
    'hero.cta.secondary': 'Obejrzyj Galerię',
    'hero.stats.graduates': 'Absolwentów',
    'hero.stats.experience': 'Lat Doświadczenia',
    'hero.stats.placement': 'Zatrudnienie',
    'hero.stats.instructors': 'Mistrzów Instruktorów',

    // Features
    'features.expert.title': 'Ekspert Instruktorzy',
    'features.expert.description': 'Ucz się od najlepszych mistrzów fryzjerstwa w Warszawie',
    'features.hands.title': 'Praktyczne Szkolenie',
    'features.hands.description': 'Zdobądź prawdziwe doświadczenie z naszym praktycznym podejściem',
    'features.career.title': 'Wsparcie Kariery',
    'features.career.description': 'Pomoc w znalezieniu pracy i rozwoju kariery po ukończeniu',
    'features.modern.title': 'Nowoczesne Techniki',
    'features.modern.description': 'Najnowsze trendy i techniki w branży fryzjerskiej',

    // About Section
    'about.title': 'O Nas',
    'about.subtitle': 'Dlaczego Wybierać K&K Academy',
    'about.description': 'Z wieloletnim doświadczeniem i pasją do edukacji, jesteśmy wiodącą akademią fryzjerską w Warszawie.',

    // Courses
    'courses.title': 'Nasze Kursy',
    'courses.subtitle': 'Wybierz idealny kurs dla swojego poziomu i celów kariery',
    'courses.beginner': 'Kurs Podstawowy',
    'courses.advanced': 'Kurs Zaawansowany', 
    'courses.master': 'Kurs Mistrzowski',
    'courses.specialty': 'Kursy Specjalistyczne',
    'courses.view.all': 'Zobacz Wszystkie Kursy',
    'courses.enroll': 'Zapisz się',
    'courses.learn.more': 'Dowiedz się więcej',
    'courses.duration': 'Czas trwania',
    'courses.level': 'Poziom',
    'courses.price': 'Cena',
    'courses.upcoming': 'Najbliższe terminy',
    'courses.cta.title': 'Gotowy na rozpoczęcie swojej drogi fryzjera?',
    'courses.cta.description': 'Dołącz do setek odnoszących sukcesy absolwentów, którzy przekształcili swoje życie dzięki naszym kompleksowym programom szkoleniowym.',
    'courses.cta.button': 'Dołącz do jednodniowego bezpłatnego kursu',

    // Instructors
    'instructors.title': 'Nasi Instruktorzy',
    'instructors.subtitle': 'Mistrzowie Fryzjerstwa',
    'instructors.description': 'Poznaj naszych doświadczonych instruktorów, którzy poprowadzą Cię przez całą podróż edukacyjną.',

    // Testimonials
    'testimonials.title': 'Historie Sukcesu Studentów',
    'testimonials.subtitle': 'Historie Sukcesu',
    'testimonials.description': 'Poznaj opinię naszych absolwentów, którzy przekształcili swoją pasję w dochodowe kariery i udane biznesy.',

    // Gallery
    'gallery.title': 'Nasza Galeria',
    'gallery.subtitle': 'Zobacz nasze prace',
    'gallery.description': 'Odkryj niesamowitą pracę naszych studentów i instruktorów.',

    // Contact
    'contact.title': 'Skontaktuj się z nami',
    'contact.subtitle': 'Masz pytania? Jesteśmy tutaj, aby pomóc',
    'contact.name': 'Imię i nazwisko',
    'contact.email': 'Email',
    'contact.phone': 'Telefon',
    'contact.message': 'Wiadomość',
    'contact.program': 'Wybierz program',
    'contact.submit': 'Wyślij wiadomość',
    'contact.info.title': 'Informacje kontaktowe',
    'contact.info.address': 'Adres',
    'contact.info.phone': 'Telefon',
    'contact.info.email': 'Email',
    'contact.info.hours': 'Godziny otwarcia',

    // Footer
    'footer.description': 'Profesjonalna akademia fryzjerska w Warszawie oferująca kompleksowe kursy i szkolenia.',
    'footer.quick.links': 'Szybkie linki',
    'footer.contact.info': 'Informacje kontaktowe',
    'footer.follow': 'Śledź nas',
    'footer.rights': 'Wszystkie prawa zastrzeżone.',

    // Blog
    'blog.title': 'Nasz Blog',
    'blog.subtitle': 'Najnowsze wiadomości i wskazówki',
    'blog.read.more': 'Czytaj więcej',
    'blog.view.all': 'Zobacz wszystkie posty',

    // CTA
    'cta.title': 'Rozpocznij swoją karierę już dziś',
    'cta.description': 'Dołącz do tysięcy odnoszących sukcesy absolwentów, którzy przekształcili swoją pasję w dochodową karierę.',
    'cta.button': 'Zapisz się teraz',

    // Common
    'common.loading': 'Ładowanie...',
    'common.error': 'Wystąpił błąd',
    'common.success': 'Sukces!',
    'common.close': 'Zamknij',
    'common.save': 'Zapisz',
    'common.cancel': 'Anuluj',
    'common.edit': 'Edytuj',
    'common.delete': 'Usuń',
    'common.view': 'Zobacz',
    'common.back': 'Wstecz',
    'common.next': 'Dalej',
    'common.previous': 'Poprzedni',

    // Additional translations for missing components
    'our.vibe': 'Nasza Atmosfera!',
    'programs.fundamentals': 'Podstawy Fryzjerstwa',
    'programs.master': 'Techniki Mistrzowskie', 
    'programs.business': 'Mistrzostwo Biznesowe',
    'programs.private': 'Lekcje Prywatne',
    'quicklinks.about': 'O Nas',
    'quicklinks.admissions': 'Przyjęcia',
    'quicklinks.financial': 'Pomoc Finansowa',
    'quicklinks.portal': 'Portal Studenta',
    'copyright': '© 2024 K&K Barber Academy. Wszystkie prawa zastrzeżone.',
    'policies.privacy': 'Polityka Prywatności',
    'policies.terms': 'Warunki Świadczenia Usług',
    'policies.handbook': 'Podręcznik Studenta',
    'working.hours': 'Godziny pracy:',
    'blog.latest': 'Najnowsze Spostrzeżenia',
    'blog.tips': 'Wskazówki, trendy i zasoby, które utrzymają Cię na czubku świata fryzjerskiego.',
    'upcoming.dates': 'Nadchodzące terminy',
    'show.all': 'Pokaż wszystkie',
    'show.less': 'Pokaż mniej',
    'dates': 'terminy',
    'testimonials.see.student.works': 'Zobacz Wszystkie Prace Studentów',
    'testimonials.see.success.stories': 'Wszystkie Historie Sukcesu',
    'free.course': 'Darmowy Kurs',
    'not.sure': 'Nie jestem pewny',
    'senior.barber.instructor': 'Starszy Instruktor Fryzjerski',
    'send.inquiry': 'Wyślij Zapytanie',
    'your.name': 'Twoje imię',
    'your.email': 'Twój email',
    'select.program': 'Wybierz program...',
    'program.interest': 'Zainteresowanie programem',
    
    // Course Translation Keys
    'course.free.title': 'Jednodniowy Darmowy Kurs Fryzjerski',
    'course.free.subtitle': 'Poznaj prawdziwy smak świata fryzjerstwa – za darmo',
    'course.free.description': 'Zastanawiasz się nad zostaniem fryzjerem, ale nie wiesz od czego zacząć? Nasz jednodniowy darmowy kurs to doskonały sposób na doświadczenie tego, jak naprawdę jest być częścią profesjonalnej akademii fryzjerskiej.',
    'course.free.badge': 'Darmowy Kurs',
    'course.beginner.title': 'Kurs Fryzjerski dla Początkujących – Od Zera do Fryzjera',
    'course.beginner.subtitle': 'Zacznij nowy zawód z pełnym przygotowaniem i pewnością siebie',
    'course.beginner.description': 'Intensywny 24-dniowy program (pon-sob, 12-20), który przeprowadza absolutnych początkujących do profesjonalnych fryzjerów poprzez teorię, praktykę na manekinach i codzienną pracę na żywych modelach.',
    'course.beginner.badge': 'Początkujący',
    'course.advanced.title': 'Kurs Zaawansowany dla Fryzjerów',
    'course.advanced.subtitle': 'Poszerz swoje umiejętności i naucz się najnowszych technik',
    'course.advanced.description': '3-dniowy bootcamp (pon-sob, 12-20) dla aktywnych fryzjerów (min. 2 lata) skupiający się na nowoczesnych strzyżeniach, zaawansowanych fade i premium pracy z brodą.',
    'course.advanced.badge': 'Zaawansowany',
    'course.specialist.title': 'Kurs Specjalistyczny – Trendy i Nowe Techniki',
    'course.specialist.subtitle': 'Odśwież umiejętności i opanuj globalne trendy',
    'course.specialist.description': '2-tygodniowy program (pon-sob, 12-19) dla fryzjerów/hairdresserów chcących przyjąć najnowsze globalne trendy w strzyżeniach, fade i stylizacji brody.',
    'course.specialist.badge': 'Specjalista',
    'instructor.about.richer': 'Ekspert w nowoczesnych technikach strzyżenia i klasycznych stylach fryzjerskich z latami profesjonalnego doświadczenia.',
    'instructor.experience.richer': 'Profesjonalny fryzjer specjalizujący się w precyzyjnych strzyżeniach i współczesnym stylizowaniu.',
    'instructor.about.apo': 'Pasjonat edukacji i wykwalifikowany fryzjer poświęcony szkoleniu następnej generacji profesjonalistów.',
    'instructor.experience.apo': 'Doświadczony fryzjer i instruktor z ekspertyzą w zaawansowanych technikach strzyżenia.',
    'instructor.about.bartosz': 'Kreatywny stylista skupiony na nowoczesnych trendach i spersonalizowanych doświadczeniach klientów.',
    'instructor.experience.bartosz': 'Wykwalifikowany fryzjer specjalizujący się w kreatywnych strzyżeniach i współczesnym stylizowaniu włosów.',
    'instructor.about.ali': 'Poświęcony profesjonalista z ekspertyzą w tradycyjnych i nowoczesnych technikach fryzjerskich.',
    'instructor.experience.ali': 'Doświadczony fryzjer z pasją do dostarczania wyjątkowych usług pielęgnacyjnych.',
    'instructor.about.tomasz': 'Doświadczony profesjonalista łączący praktyczne umiejętności fryzjerskie z doskonałością w nauczaniu.',
    'instructor.experience.tomasz': 'Profesjonalny fryzjer i edukator zaangażowany w dzielenie się wiedzą i umiejętnościami.',
    'testimonial.1.quote': 'Najlepsze miejsce w Warszawie, aby szybko i przede wszystkim dobrze nauczyć się zawodu od podstaw. Właśnie skończyłem kurs, chłopaki pomogli z finansowaniem kursu i znaleźli mi pracę zaraz po ukończeniu. Bardzo polecam i dziękuję!',
    'testimonial.1.name': 'Angelika Ziółkowska',
    'testimonial.1.title': 'Absolwent • 5-gwiazdkowa opinia Google',
    'testimonial.2.quote': 'Miałem przyjemność uczestniczyć w 3-dniowym szkoleniu pod opieką Tomka i Alego. Jestem zachwycony efektami szkolenia. Świetna atmosfera i wspaniałi edukatorzy. Chłopaki dali nam ogromną dawkę wiedzy i wskazówek dotyczących tworzenia portfolio. Bardzo polecam!',
    'testimonial.2.name': 'Agata Antoniewicz',
    'testimonial.2.title': 'Absolwent • 5-gwiazdkowa opinia Google',
    'testimonial.3.quote': 'Pomimo czasu, który minął od końca kursu, postanowiłem zostawić opinię. Uczestniczyłem w miesięcznym kursie "Barber od podstaw" w K&K Academy i jestem pod wrażeniem poziomu profesjonalizmu i jakości szkolenia. Edukatorzy Tomek, Bartek i Ali wykazali się nie tylko wiedzą teoretyczną, ale też imponującymi umiejętnościami praktycznymi. Teraz, 6 miesięcy po ukończeniu kursu, z powodzeniem prowadzę własny salon i cieszę się, że miałem okazję uczestniczyć w kursie od podstaw z chłopakami.',
    'testimonial.3.name': 'Sharp Cut Barber',
    'testimonial.3.title': 'Właściciel Salonu • 5-gwiazdkowa opinia Google',
    'common.graduate': 'Absolwent',
    'common.review': 'opinia Google',
    'common.star': 'gwiazdkowa',
    'common.show.more': 'Pokaż więcej',
    'common.show.less': 'Pokaż mniej',
    'common.all': 'wszystkie',
    'common.dates': 'terminy',
    'common.upcoming': 'Nadchodzące',
    'months.january': 'Styczeń',
    'months.february': 'Luty',
    'months.march': 'Marzec',
    'months.april': 'Kwiecień',
    'months.may': 'Maj',
    'months.june': 'Czerwiec',
    'months.july': 'Lipiec',
    'months.august': 'Sierpień',
    'months.september': 'Wrzesień',
    'months.october': 'Październik',
    'months.november': 'Listopad',
    'months.december': 'Grudzień',
    
    // About Section Translation Keys  
    'about.features.certified': 'Programy certyfikowane przez państwo z uznaniem branży',
    'about.features.handson': 'Szkolenie praktyczne z profesjonalnym sprzętem',
    'about.features.placement': 'Pomoc w znalezieniu pracy i ciągłe wsparcie',
    'about.learn.more': 'Dowiedz się więcej o nas',
    'about.certified.excellence': 'Certyfikowana doskonałość',
    'about.state.licensed': 'Akademia licencjonowana przez państwo',
    'common.free': 'BEZPŁATNE',
    
    // Course Translation Keys
    'courses.enroll.now': 'Zapisz się teraz',
    'courses.cta.title': 'Gotowy, aby rozpocząć karierę barbera?',
    'courses.cta.description': 'Dołącz do naszej akademii i opanuj umiejętności, które wyróżnią cię w branży fryzjerskiej.',
    'courses.cta.button': 'Rozpocznij swoją podróż',
    'course.duration.4hours': '4 godziny',
    'course.duration.1month': '1 miesiąc',
    'course.duration.3days': '3 dni',
    'course.duration.2weeks': '2 tygodnie',
    'course.certification.experience': 'Certyfikat doświadczenia',
    'course.certification.professional': 'Profesjonalny certyfikat',
    'course.certification.advanced': 'Zaawansowany certyfikat',
    'course.certification.specialist': 'Certyfikat specjalisty',

    // Instructors Translation Keys
    'instructors.title': 'Poznaj naszych instruktorów',
    'instructors.subtitle': 'Eksperci branżowi',
    'instructors.description': 'Nasi doświadczeni fryzjerzy to praktycy z wieloletnim doświadczeniem w najlepszych salonach w Warszawie. Uczysz się od najlepszych.',
    'senior.barber.instructor': 'Starszy instruktor fryzjer',
    'instructor.richer.karimov': 'Richer Karimov',
    'instructor.apo.karimov': 'Apo Karimov',
    'instructor.bartosz.kaczorowski': 'Bartosz Kaczorowski',
    'instructor.ali.karimov': 'Ali Karimov',
    'instructor.tomasz.kaczorowski': 'Tomasz Kaczorowski',

    // Contact Translation Keys
    'contact.title': 'Rozpocznij swoją',
    'contact.title.highlight': 'podróż',
    'contact.title.today': 'dzisiaj',
    'contact.subtitle': 'Gotowy, aby przekształcić swoją pasję w profesjonalną karierę? Skontaktuj się z naszym zespołem rekrutacyjnym, aby dowiedzieć się więcej o naszych programach i zaplanować wizytę w akademii.',
    'contact.visit.campus': 'Odwiedź naszą akademię',
    'contact.call.us': 'Zadzwoń do nas',
    'contact.email.us': 'Napisz do nas',
    'contact.hours': 'Godziny pracy',
    'contact.hours.schedule': 'Poniedziałek-Piątek: 12:00 - 21:00, Sobota: 12:00 - 17:00',
    'contact.form.title': 'Uzyskaj więcej informacji',
    'contact.form.first.name': 'Imię',
    'contact.form.last.name': 'Nazwisko',
    'contact.form.email': 'Email',
    'contact.form.phone': 'Telefon',
    'contact.form.program': 'Program zainteresowania',
    'contact.form.message': 'Wiadomość',
    'contact.form.submit': 'Wyślij zapytanie',
    'contact.form.required': 'Wypełnij wymagane pola',
    'contact.form.required.desc': 'Imię, Nazwisko i Email są wymagane.',
    'contact.form.thank.you': 'Dziękujemy za zainteresowanie!',
    'contact.form.thank.you.desc': 'Skontaktujemy się z Tobą wkrótce z dodatkowymi informacjami.',
    'contact.program.free': 'Bezpłatny kurs',
    'contact.program.beginner': 'Kurs podstawowy (1 miesiąc)',
    'contact.program.advanced': 'Kurs zaawansowany (3 dni)',
    'contact.program.specialist': 'Kurs specjalistyczny (2 tygodnie)',
    'contact.program.select': 'Wybierz program',

    // Gallery Translation Keys  
    'gallery.title': 'Nasza',
    'gallery.title.highlight': 'Galeria',
    'gallery.subtitle': 'Profesjonalne środowisko',
    'gallery.description': 'Zobacz naszą nowoczesną akademię, profesjonalny sprzęt i prace uczniów w akcji.',
    'gallery.see.all.student.works': 'Zobacz wszystkie prace uczniów',
    'gallery.all.success.stories': 'Wszystkie historie sukcesu',
    'gallery.view.full': 'Zobacz pełną galerię',

    // Blog Translation Keys
    'blog.latest': 'Najnowsze wpisy',
    'blog.tips': 'Zdobądź profesjonalne wskazówki, trendy branżowe i wgląd w ekspertyzy od naszych ekspertów.',
    'blog.read.more': 'Czytaj więcej',

    // CTA Enroll Translation Keys
    'cta.enroll.title': 'Rozpocznij swoją podróż fryzjerską już dziś',
    'cta.enroll.description': 'Aplikuj teraz i dołącz do naszej społeczności elitarnych fryzjerów kształtujących przyszłość stylu.',
    'cta.enroll.button': 'Rozpocznij swoją podróż',

    // Page Translation Keys
    'course.not.found': 'Kurs nie został znaleziony.',
    'page.gallery.title': 'Pełna',
    'page.gallery.title.highlight': 'Galeria',
    'page.gallery.loading': 'Odkryj naszą kompletną kolekcję prac',
    'page.gallery.explore': 'Sprawdź naszą kompletną kolekcję ${count} profesjonalnych prac i momentów treningowych',
    'page.students.title': 'Prace',
    'page.students.title.highlight': 'Uczniów',
    'page.students.explore': 'Zobacz niesamowite transformacje i umiejętności naszych uczniów',
    'page.success.title': 'Historie',
    'page.success.title.highlight': 'Sukcesu',
    'page.success.explore': 'Poznaj inspirujące historie naszych absolwentów',
    'page.back.home': 'Powrót do strony głównej',
    'page.apply.now': 'Aplikuj teraz',
    'page.showcased.works': 'prezentowanych prac',
    'page.blog.title': 'Akademia',
    'page.blog.title.highlight': 'Wskazówki',
    'page.blog.subtitle': 'Wiadomości, porady i trendy ze świata nowoczesnego fryzjerstwa.',

    // Blog Post Translation Keys
    'blog.post.career.title': 'Jak rozpocząć karierę w fryzjerstwie',
    'blog.post.career.excerpt': 'Myślisz o zostaniu fryzjerem? Oto jak mogą wyglądać twoje pierwsze 30 dni...',
    'blog.post.fade.title': 'Top 5 technik fade na 2025 rok',
    'blog.post.fade.excerpt': 'Wyprzedź konkurencję dzięki tym niezbędnym wariacjom fade, o które będzie pytać każdy klient.',
    'blog.post.toolkit.title': 'Zestaw fryzjera: Niezbędne vs. Miłe w posiadaniu',
    'blog.post.toolkit.excerpt': 'Od maszynki do grzebieni, oto nasz ostateczny przewodnik po budowaniu profesjonalnego zestawu bez przepłacania.',
    'blog.tag.beginner': 'Początkujący',
    'blog.tag.trends': 'Trendy',
    'blog.tag.tools': 'Narzędzia',
    'blog.filter.all': 'Wszystkie',

    // Contact Page Translation Keys
    'contact.title': 'Skontaktuj się',
    'contact.title.highlight': 'z nami',
    'contact.title.today': 'już dziś',
    'contact.subtitle': 'Gotowy, aby rozpocząć swoją podróż w fryzjerstwie? Nasz zespół przyjęć jest tutaj, aby pomóc Ci każdego kroku.',
    'contact.visit.campus': 'Odwiedź nasz kampus',
    'contact.call.us': 'Zadzwoń do nas',
    'contact.email.us': 'Napisz do nas',
    'contact.hours': 'Godziny pracy',
    'contact.hours.weekdays': 'Pon-Pt: 12:00 - 21:00',
    'contact.hours.saturday': 'Sob: 12:00 - 17:00',
    'contact.hours.sunday': 'Niedz: Zamknięte',
    'contact.form.first.name': 'Imię',
    'contact.form.last.name': 'Nazwisko',
    'contact.form.email': 'Email',
    'contact.form.phone': 'Telefon',
    'contact.form.program': 'Program',
    'contact.form.program.placeholder': 'Wybierz program...',
    'contact.form.program.basic': 'Podstawowy kurs fryzjerski',
    'contact.form.program.advanced': 'Zaawansowane techniki',
    'contact.form.program.complete': 'Kompletny program',
    'contact.form.program.free': 'Darmowy kurs',
    'contact.form.message': 'Wiadomość',
    'contact.form.message.placeholder': 'Opowiedz nam o swoich celach i doświadczeniu...',
    'contact.form.title': 'Wyślij nam wiadomość',
    'contact.form.submit': 'Wyślij wiadomość',
    'contact.form.required': 'Wymagane pola',
    'contact.form.required.desc': 'Proszę wypełnić wszystkie wymagane pola.',
    'contact.form.thank.you': 'Dziękujemy!',
    'contact.form.thank.you.desc': 'Twoja wiadomość została wysłana. Wkrótce się z Tobą skontaktujemy.',
    'contact.page.title': 'Kontakt',
    'contact.page.highlight': 'K&K Academy',
    'contact.page.subtitle': 'Masz pytania dotyczące naszych programów, cen lub zapisów? Skontaktuj się z nami, a nasz zespół przyjęć chętnie pomoże.',
    'contact.form.error': 'Błąd wysyłania wiadomości',
    'contact.form.error.desc': 'Spróbuj ponownie później.',
    'contact.form.success': 'Wiadomość wysłana!',
    'contact.form.success.desc': 'Wkrótce się z Tobą skontaktujemy.',

    // Course Details Translation Keys
    'course.not.found': 'Kurs nie znaleziony',
    'course.overview': 'Przegląd kursu',
    'course.curriculum': 'Program nauczania',
    'course.instructors': 'Instruktorzy',
    'course.gallery': 'Galeria',
    'course.book.now': 'Zapisz się teraz',
    'course.duration': 'Czas trwania',
    'course.students': 'Uczniowie',
    'course.certification': 'Certyfikacja',
    'course.what.learn': 'Czego się nauczysz',
    'course.upcoming.dates': 'Nadchodzące terminy',
    'course.enroll.today': 'Zapisz się dziś',
    'course.meet.instructors': 'Poznaj instruktorów',
    'course.select.date': 'Wybierz preferowany termin rozpoczęcia',
    'course.audience': 'Dla kogo jest ten kurs',
    'course.how.works': 'Jak działa kurs',
    'course.whats.included': 'Co jest zawarte',
    'course.outcomes': 'Pod koniec będziesz w stanie…',
    'course.gallery.title': 'Kurs w akcji',
    'course.gallery.subtitle': 'Przeglądaj momenty z naszego praktycznego szkolenia.',
    'course.certificate.title': 'Certyfikat i Akredytacja',
    'course.certificate.description': 'Po ukończeniu kursu otrzymasz certyfikat wydany przez K&K Academy, uznaną instytucję szkoleniową dla fryzjerów.',
    'course.certificate.accredited': 'Akredytowany certyfikat',
    'course.certificate.industry': 'Uznawany w branży',
    'course.certificate.portfolio': 'Portfolio prac',
    'course.pricing.title': 'Cennik i Plany',
    'course.pricing.description': 'Wybierz plan, który najlepiej odpowiada Twoim potrzebom i budżetowi.',
    'course.pricing.full.payment': 'Płatność pełna',
    'course.pricing.installments': 'Płatność ratalna',
    'course.pricing.contact': 'Skontaktuj się po szczegóły',
    'course.faq.title': 'Często zadawane pytania',
    'course.faq.experience.q': 'Czy potrzebuję wcześniejszego doświadczenia?',
    'course.faq.experience.a': 'Nie, nasze kursy dla początkujących są zaprojektowane dla osób bez wcześniejszego doświadczenia we fryzjerstwie.',
    'course.faq.tools.q': 'Czy muszę kupować własne narzędzia?',
    'course.faq.tools.a': 'Nie, wszystkie narzędzia i materiały są zapewnione podczas kursu. Otrzymasz też listę rekomendowanych narzędzi do zakupu.',
    'course.faq.job.q': 'Czy pomagacie w znalezieniu pracy?',
    'course.faq.job.a': 'Tak, oferujemy wsparcie w znalezieniu pracy i mamy partnerstwa z lokalnymi salonami fryzjerskimi.',
    'course.cta.final.title': 'Rozpocznij swoją podróż już dziś',
    'course.cta.final.description': 'Dołącz do setek zadowolonych absolwentów, którzy zbudowali udane kariery w fryzjerstwie.',
    'course.cta.final.button': 'Zapisz się teraz',

    // Beginner Course (ID: 1) Specific Translations
    'course.beginner.skills.0': 'Klasyczne i nowoczesne fryzury',
    'course.beginner.skills.1': 'Wygolenia maszynką (niskie/średnie/wysokie)',
    'course.beginner.skills.2': 'Praca brzytwą i detale',
    'course.beginner.skills.3': 'Modelowanie i pielęgnacja brody',
    
    'course.beginner.audience.0': 'Osoby bez doświadczenia',
    'course.beginner.audience.1': 'Osoby zmieniające karierę',
    'course.beginner.audience.2': 'Uczniowie po szkole',
    
    'course.beginner.howItWorks.0': 'Teoria',
    'course.beginner.howItWorks.1': 'Praktyka na manekinach',
    'course.beginner.howItWorks.2': 'Prawdziwi klienci',
    'course.beginner.howItWorks.0.desc': 'Interaktywne wykłady i demonstracje',
    'course.beginner.howItWorks.1.desc': 'Rozwijaj pamięć mięśniową bezpiecznie',
    'course.beginner.howItWorks.2.desc': 'Strzyżenia pod nadzorem na żywych modelach',
    
    'course.beginner.includes.0': 'Prezent - profesjonalne nożyczki i grzebień',
    'course.beginner.includes.1': 'Wszystkie narzędzia zapewnione',
    'course.beginner.includes.2': 'Certyfikat ukończenia',
    
    'course.beginner.outcomes.0': 'Wykonywać nowoczesne strzyżenia i wygolenia',
    'course.beginner.outcomes.1': 'Pewnie stylizować brody',
    'course.beginner.outcomes.2': 'Rozpocząć karierę fryzjera',

    // Instructor Details Translation Keys
    'instructor.not.found': 'Instruktor nie znaleziony',
    'instructor.apply.now': 'Aplikuj teraz',
    'instructor.experience': 'Doświadczenie',
    'instructor.specializations': 'Specjalizacje',
    'instructor.about': 'O instrukturze',
    'instructor.contact': 'Skontaktuj się',
    'senior.barber.instructor': 'Starszy Instruktor Fryzjerski',

    // About Section CTA
    'about.cta': 'Rozpocznij swoją podróż',

    // Individual Instructor Details
    'instructor.1.about': 'Ekspert w klasycznych technikach fryzjerskich z ponad 10-letnim doświadczeniem. Specjalizuje się w precyzyjnych strzyżeniach i stylizacji brody.',
    'instructor.1.experience': 'Doświadczenie: 12+ lat',
    'instructor.2.about': 'Mistrz nowoczesnych trendów i kreatywnych stylizacji. Prowadzi warsztaty dla zaawansowanych uczniów.',
    'instructor.2.experience': 'Doświadczenie: 8+ lat',
    'instructor.3.about': 'Specjalista od tradycyjnych technik i precyzyjnego golenia. Mentor dla nowych instruktorów.',
    'instructor.3.experience': 'Doświadczenie: 15+ lat',
    'instructor.4.about': 'Ekspert w nowoczesnych technikach strzyżenia i koloryzacji. Certyfikowany instruktor międzynarodowy.',
    'instructor.4.experience': 'Doświadczenie: 10+ lat',
    'instructor.5.about': 'Mistrz klasycznego fryzjerstwa i stylizacji. Prowadzi kursy dla zaawansowanych.',
    'instructor.5.experience': 'Doświadczenie: 14+ lat',
  },

  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.courses': 'Courses',
    'nav.gallery': 'Gallery',
    'nav.instructors': 'Instructors',
    'nav.students': 'Students',
    'nav.success': 'Success Stories',
    'nav.blog': 'Blog',
    'nav.contact': 'Contact',
    'nav.enroll': 'Enroll Now',

    // Hero Section
    'hero.title': 'K&K Barber Academy',
    'hero.subtitle': 'Master the Art of Barbering with Warsaw\'s Leading Instructors',
    'hero.description': 'Join our professional academy and transform your passion into a profitable career. Comprehensive training, hands-on experience, and career support.',
    'hero.cta.primary': 'Enroll in Course',
    'hero.cta.secondary': 'View Gallery',
    'hero.stats.graduates': 'Graduates',
    'hero.stats.experience': 'Years Experience',
    'hero.stats.placement': 'Job Placement',
    'hero.stats.instructors': 'Master Instructors',

    // Features
    'features.expert.title': 'Expert Instructors',
    'features.expert.description': 'Learn from the best master barbers in Warsaw',
    'features.hands.title': 'Hands-on Training',
    'features.hands.description': 'Gain real experience with our practical approach',
    'features.career.title': 'Career Support',
    'features.career.description': 'Job placement assistance and career development after graduation',
    'features.modern.title': 'Modern Techniques',
    'features.modern.description': 'Latest trends and techniques in the barbering industry',

    // About Section
    'about.title': 'About Us',
    'about.subtitle': 'Why Choose K&K Academy',
    'about.description': 'With years of experience and a passion for education, we are Warsaw\'s leading barber academy.',

    // Courses
    'courses.title': 'Our Courses',
    'courses.subtitle': 'Choose the perfect course for your skill level and career goals',
    'courses.beginner': 'Beginner Course',
    'courses.advanced': 'Advanced Course',
    'courses.master': 'Master Course',
    'courses.specialty': 'Specialty Courses',
    'courses.view.all': 'View All Courses',
    'courses.enroll': 'Enroll',
    'courses.learn.more': 'Learn More',
    'courses.duration': 'Duration',
    'courses.level': 'Level',
    'courses.price': 'Price',
    'courses.upcoming': 'Upcoming Dates',
    'courses.cta.title': 'Ready to Start Your Barber Journey?',
    'courses.cta.description': 'Join hundreds of successful graduates who\'ve transformed their lives through our comprehensive training programs.',
    'courses.cta.button': 'Join One Day Free Course',

    // Instructors
    'instructors.title': 'Our Instructors',
    'instructors.subtitle': 'Master Barbers',
    'instructors.description': 'Meet our experienced instructors who will guide you through your entire educational journey.',

    // Testimonials
    'testimonials.title': 'Student Success Stories',
    'testimonials.subtitle': 'Success Stories',
    'testimonials.description': 'Hear from our graduates who\'ve transformed their passion into profitable careers and successful businesses.',

    // Gallery
    'gallery.title': 'Our Gallery',
    'gallery.subtitle': 'See our work',
    'gallery.description': 'Discover the amazing work of our students and instructors.',

    // Contact
    'contact.title': 'Contact Us',
    'contact.subtitle': 'Have questions? We\'re here to help',
    'contact.name': 'Full Name',
    'contact.email': 'Email',
    'contact.phone': 'Phone',
    'contact.message': 'Message',
    'contact.program': 'Select Program',
    'contact.submit': 'Send Message',
    'contact.info.title': 'Contact Information',
    'contact.info.address': 'Address',
    'contact.info.phone': 'Phone',
    'contact.info.email': 'Email',
    'contact.info.hours': 'Opening Hours',

    // Footer
    'footer.description': 'Professional barber academy in Warsaw offering comprehensive courses and training.',
    'footer.quick.links': 'Quick Links',
    'footer.contact.info': 'Contact Information',
    'footer.follow': 'Follow Us',
    'footer.rights': 'All rights reserved.',

    // Blog
    'blog.title': 'Our Blog',
    'blog.subtitle': 'Latest news and tips',
    'blog.read.more': 'Read More',
    'blog.view.all': 'View All Posts',

    // CTA
    'cta.title': 'Start Your Career Today',
    'cta.description': 'Join thousands of successful graduates who have transformed their passion into a profitable career.',
    'cta.button': 'Enroll Now',

    // Common
    'common.loading': 'Loading...',
    'common.error': 'An error occurred',
    'common.success': 'Success!',
    'common.close': 'Close',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.edit': 'Edit',
    'common.delete': 'Delete',
    'common.view': 'View',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.previous': 'Previous',

    // Additional translations for missing components
    'our.vibe': 'Our Vibe!',
    'programs.fundamentals': 'Barber Fundamentals',
    'programs.master': 'Master Techniques',
    'programs.business': 'Business Mastery',
    'programs.private': 'Private Lessons',
    'quicklinks.about': 'About Us',
    'quicklinks.admissions': 'Admissions',
    'quicklinks.financial': 'Financial Aid',
    'quicklinks.portal': 'Student Portal',
    'copyright': '© 2024 K&K Barber Academy. All rights reserved.',
    'policies.privacy': 'Privacy Policy',
    'policies.terms': 'Terms of Service',
    'policies.handbook': 'Student Handbook',
    'working.hours': 'Working hours:',
    'blog.latest': 'Latest Insights',
    'blog.tips': 'Tips, trends, and resources to keep you at the cutting edge of the barbering world.',
    'upcoming.dates': 'Upcoming Dates',
    'show.all': 'Show all',
    'show.less': 'Show less',
    'dates': 'dates',
    'testimonials.see.student.works': 'See All Student Works',
    'testimonials.see.success.stories': 'All Success Stories',
    'free.course': 'Free Course',
    'not.sure': 'Not sure yet',
    'senior.barber.instructor': 'Senior Barber Instructor',
    'send.inquiry': 'Send Inquiry',
    'your.name': 'Your name',
    'your.email': 'Your email',
    'select.program': 'Select program...',
    'program.interest': 'Program Interest',
    
    // About Section Translation Keys  
    'about.features.certified': 'State-certified programs with industry recognition',
    'about.features.handson': 'Hands-on training with professional-grade equipment',
    'about.features.placement': 'Career placement assistance and ongoing support',
    'about.learn.more': 'Learn More About Us',
    'about.certified.excellence': 'Certified Excellence',
    'about.state.licensed': 'State Licensed Academy',
    'common.free': 'FREE',
    
    // Course Translation Keys
    'courses.enroll.now': 'Enroll Now',
    'courses.cta.title': 'Ready to Start Your Barbering Career?',
    'courses.cta.description': 'Join our academy and master the skills that will set you apart in the barbering industry.',
    'courses.cta.button': 'Start Your Journey',
    'course.duration.4hours': '4 hours',
    'course.duration.1month': '1 month',
    'course.duration.3days': '3 days',
    'course.duration.2weeks': '2 weeks',
    'course.certification.experience': 'Experience Certificate',
    'course.certification.professional': 'Professional Certificate',
    'course.certification.advanced': 'Advanced Certificate',
    'course.certification.specialist': 'Specialist Certificate',

    // Instructors Translation Keys
    'instructors.title': 'Meet Our Instructors',
    'instructors.subtitle': 'Industry Experts',
    'instructors.description': 'Our experienced barbers are practitioners with years of experience in Warsaw\'s top salons. Learn from the best.',
    'senior.barber.instructor': 'Senior Barber Instructor',
    'instructor.richer.karimov': 'Richer Karimov',
    'instructor.apo.karimov': 'Apo Karimov',
    'instructor.bartosz.kaczorowski': 'Bartosz Kaczorowski',
    'instructor.ali.karimov': 'Ali Karimov',
    'instructor.tomasz.kaczorowski': 'Tomasz Kaczorowski',

    // Contact Translation Keys
    'contact.title': 'Start Your',
    'contact.title.highlight': 'Journey',
    'contact.title.today': 'Today',
    'contact.subtitle': 'Ready to transform your passion into a professional career? Get in touch with our admissions team to learn more about our programs and schedule a campus tour.',
    'contact.visit.campus': 'Visit Our Campus',
    'contact.call.us': 'Call Us',
    'contact.email.us': 'Email Us',
    'contact.hours': 'Hours',
    'contact.hours.schedule': 'Mon-Fri: 12:00 - 21:00, Sat: 12:00 - 17:00',
    'contact.form.title': 'Get More Information',
    'contact.form.first.name': 'First Name',
    'contact.form.last.name': 'Last Name',
    'contact.form.email': 'Email',
    'contact.form.phone': 'Phone',
    'contact.form.program': 'Program Interest',
    'contact.form.message': 'Message',
    'contact.form.submit': 'Send Inquiry',
    'contact.form.required': 'Please fill in required fields',
    'contact.form.required.desc': 'First Name, Last Name, and Email are required.',
    'contact.form.thank.you': 'Thank you for your interest!',
    'contact.form.thank.you.desc': 'We will contact you soon with more information.',
    'contact.program.free': 'Free Course',
    'contact.program.beginner': 'Beginner Course (1 month)',
    'contact.program.advanced': 'Advanced Course (3 days)',
    'contact.program.specialist': 'Specialist Course (2 weeks)',
    'contact.program.select': 'Select a program',

    // Gallery Translation Keys  
    'gallery.view.full': 'View Full Gallery',

    // Blog Translation Keys
    'blog.latest': 'Latest Insights',
    'blog.tips': 'Get professional tips, industry trends, and expert insights from our professionals.',
    'blog.read.more': 'Read More',

    // CTA Enroll Translation Keys
    'cta.enroll.title': 'Kick-start Your Barber Journey Today',
    'cta.enroll.description': 'Apply now and join our community of elite barbers shaping the future of style.',
    'cta.enroll.button': 'Start Your Journey',

    // Page Translation Keys
    'course.not.found': 'Course not found.',
    'page.gallery.title': 'Full',
    'page.gallery.title.highlight': 'Gallery',
    'page.gallery.loading': 'Discover our complete collection of work',
    'page.gallery.explore': 'Explore our complete collection of ${count} professional works and training moments',
    'page.students.title': 'Student',
    'page.students.title.highlight': 'Works',
    'page.students.explore': 'See the amazing transformations and skills from our students',
    'page.success.title': 'Success',
    'page.success.title.highlight': 'Stories',
    'page.success.explore': 'Discover inspiring stories from our graduates',
    'page.back.home': 'Back to Home',
    'page.apply.now': 'Apply Now',
    'page.showcased.works': 'showcased works',
    'page.blog.title': 'Academy',
    'page.blog.title.highlight': 'Insights',
    'page.blog.subtitle': 'News, tips and trends from the world of modern barbering.',

    // Blog Post Translation Keys
    'blog.post.career.title': 'How to Start a Career in Barbering',
    'blog.post.career.excerpt': "Thinking about becoming a barber? Here's what your first 30 days might look like...",
    'blog.post.fade.title': 'Top 5 Fade Techniques for 2025',
    'blog.post.fade.excerpt': 'Stay ahead of the curve with these must-know fade variations every client will ask for.',
    'blog.post.toolkit.title': 'Barber Toolkit: Essentials vs. Nice-to-Have',
    'blog.post.toolkit.excerpt': "From clippers to combs, here's our definitive guide to building a pro kit without overspending.",
    'blog.tag.beginner': 'Beginner',
    'blog.tag.trends': 'Trends',
    'blog.tag.tools': 'Tools',
    'blog.filter.all': 'All',

    // Contact Page Translation Keys
    'contact.title': 'Contact',
    'contact.title.highlight': 'us',
    'contact.title.today': 'today',
    'contact.subtitle': 'Ready to start your barbering journey? Our admissions team is here to help you every step of the way.',
    'contact.visit.campus': 'Visit our campus',
    'contact.call.us': 'Call us',
    'contact.email.us': 'Email us',
    'contact.hours': 'Operating hours',
    'contact.hours.weekdays': 'Mon-Fri: 12 am - 9 pm',
    'contact.hours.saturday': 'Sat: 12 am – 5 pm',
    'contact.hours.sunday': 'Sun: Closed',
    'contact.form.first.name': 'First Name',
    'contact.form.last.name': 'Last Name',
    'contact.form.email': 'Email',
    'contact.form.phone': 'Phone',
    'contact.form.program': 'Program',
    'contact.form.program.placeholder': 'Select a program...',
    'contact.form.program.basic': 'Basic Barbering Course',
    'contact.form.program.advanced': 'Advanced Techniques',
    'contact.form.program.complete': 'Complete Program',
    'contact.form.program.free': 'Free Course',
    'contact.form.message': 'Message',
    'contact.form.message.placeholder': 'Tell us about your goals and experience...',
    'contact.form.title': 'Send us a message',
    'contact.form.submit': 'Send Message',
    'contact.form.required': 'Required fields',
    'contact.form.required.desc': 'Please fill in all required fields.',
    'contact.form.thank.you': 'Thank you!',
    'contact.form.thank.you.desc': 'Your message has been sent. We will be in touch shortly.',
    'contact.page.title': 'Contact',
    'contact.page.highlight': 'K&K Academy',
    'contact.page.subtitle': 'Have questions about our programs, pricing, or enrollment? Reach out and our admissions team will gladly help.',
    'contact.form.error': 'Error sending message',
    'contact.form.error.desc': 'Please try again later.',
    'contact.form.success': 'Message sent!',
    'contact.form.success.desc': 'We will be in touch shortly.',

    // Course Details Translation Keys
    'course.not.found': 'Course not found',
    'course.overview': 'Course Overview',
    'course.curriculum': 'Curriculum',
    'course.instructors': 'Instructors',
    'course.gallery': 'Gallery',
    'course.book.now': 'Book Now',
    'course.duration': 'Duration',
    'course.students': 'Students',
    'course.certification': 'Certification',
    'course.what.learn': 'What you will learn',
    'course.upcoming.dates': 'Upcoming Dates',
    'course.enroll.today': 'Enroll Today',
    'course.meet.instructors': 'Meet Your Instructors',
    'course.select.date': 'Select your preferred start date',
    'course.audience': 'Who This Course Is For',
    'course.how.works': 'How the Course Works',
    'course.whats.included': 'What\'s Included',
    'course.outcomes': 'By the end you will…',
    'course.gallery.title': 'Course in Action',
    'course.gallery.subtitle': 'Swipe through moments from our hands-on training.',
    'course.certificate.title': 'Certificate & Accreditation',
    'course.certificate.description': 'Upon completion, you will receive a certificate issued by K&K Academy, a recognized training institution for barbers.',
    'course.certificate.accredited': 'Accredited Certificate',
    'course.certificate.industry': 'Industry Recognized',
    'course.certificate.portfolio': 'Work Portfolio',
    'course.pricing.title': 'Pricing & Plans',
    'course.pricing.description': 'Choose the plan that best fits your needs and budget.',
    'course.pricing.full.payment': 'Full Payment',
    'course.pricing.installments': 'Installment Plan',
    'course.pricing.contact': 'Contact for Details',
    'course.faq.title': 'Frequently Asked Questions',
    'course.faq.experience.q': 'Do I need previous experience?',
    'course.faq.experience.a': 'No, our beginner courses are designed for people with no previous barbering experience.',
    'course.faq.tools.q': 'Do I need to buy my own tools?',
    'course.faq.tools.a': 'No, all tools and materials are provided during the course. You will also receive a list of recommended tools to purchase.',
    'course.faq.job.q': 'Do you help with job placement?',
    'course.faq.job.a': 'Yes, we offer job placement support and have partnerships with local barbershops.',
    'course.cta.final.title': 'Start Your Journey Today',
    'course.cta.final.description': 'Join hundreds of satisfied graduates who have built successful careers in barbering.',
    'course.cta.final.button': 'Enroll Now',

    // Beginner Course (ID: 1) Specific Translations
    'course.beginner.skills.0': 'Classic & modern haircuts',
    'course.beginner.skills.1': 'Clipper fading (low/mid/high)',
    'course.beginner.skills.2': 'Razor work & detailing',
    'course.beginner.skills.3': 'Beard shaping & care',
    
    'course.beginner.audience.0': 'People with no experience',
    'course.beginner.audience.1': 'Career changers',
    'course.beginner.audience.2': 'Students after school',
    
    'course.beginner.howItWorks.0': 'Theory',
    'course.beginner.howItWorks.1': 'Practice on Mannequins',
    'course.beginner.howItWorks.2': 'Real Clients',
    'course.beginner.howItWorks.0.desc': 'Interactive lectures & demos',
    'course.beginner.howItWorks.1.desc': 'Develop muscle memory safely',
    'course.beginner.howItWorks.2.desc': 'Supervised cuts on live models',
    
    'course.beginner.includes.0': 'Professional scissors & comb gift',
    'course.beginner.includes.1': 'All tools provided',
    'course.beginner.includes.2': 'Certificate of completion',
    
    'course.beginner.outcomes.0': 'Perform modern cuts & fades',
    'course.beginner.outcomes.1': 'Confidently style beards',
    'course.beginner.outcomes.2': 'Launch barber career',

    // Instructor Details Translation Keys
    'instructor.not.found': 'Instructor not found',
    'instructor.apply.now': 'Apply Now',
    'instructor.experience': 'Experience',
    'instructor.specializations': 'Specializations',
    'instructor.about': 'About Instructor',
    'instructor.contact': 'Contact',
    'senior.barber.instructor': 'Senior Barber Instructor',

    // About Section CTA
    'about.cta': 'Start Your Journey',

    // Individual Instructor Details
    'instructor.1.about': 'Expert in classical barbering techniques with over 10 years of experience. Specializes in precision cuts and beard styling.',
    'instructor.1.experience': 'Experience: 12+ years',
    'instructor.2.about': 'Master of modern trends and creative styling. Leads workshops for advanced students.',
    'instructor.2.experience': 'Experience: 8+ years',
    'instructor.3.about': 'Specialist in traditional techniques and precision shaving. Mentor to new instructors.',
    'instructor.3.experience': 'Experience: 15+ years',
    'instructor.4.about': 'Expert in modern cutting techniques and coloring. Certified international instructor.',
    'instructor.4.experience': 'Experience: 10+ years',
    'instructor.5.about': 'Master of classical barbering and styling. Leads advanced courses.',
    'instructor.5.experience': 'Experience: 14+ years',

    'course.free.title': 'One-Day Free Barbering Course',
    'course.free.subtitle': 'Get a Real Taste of the Barbering World – For Free',
    'course.free.description': 'Curious about becoming a barber, but not sure where to start? Our One-Day Free Course is the perfect way to experience what it\'s really like to be part of a professional barbering academy.',
    'course.free.badge': 'Free Course',
    'course.beginner.title': 'Beginner Barber Course – From Zero to Barber',
    'course.beginner.subtitle': 'Start a new profession with full preparation and confidence',
    'course.beginner.description': 'Intensive 24-day program (Mon–Sat, 12–20) that takes absolute beginners to professional barbers through theory, mannequin practice, and daily work on live models.',
    'course.beginner.badge': 'Beginner',
    'course.advanced.title': 'Advanced Course for Barbers',
    'course.advanced.subtitle': 'Expand your skills & learn the latest techniques',
    'course.advanced.description': '3-day bootcamp (Mon–Sat, 12–20) for active barbers (min 2 yrs) focusing on modern cuts, advanced fades, and premium beard work.',
    'course.advanced.badge': 'Advanced',
    'course.specialist.title': 'Specialist Course – Trends & New Techniques',
    'course.specialist.subtitle': 'Refresh skills & master global trends',
    'course.specialist.description': '2-week programme (Mon–Sat, 12–19) for barbers/hairdressers wanting to adopt the latest global trends in cuts, fades and beard styling.',
    'course.specialist.badge': 'Specialist',
    'instructor.about.richer': 'Expert in modern cutting techniques and classic barbering styles with years of professional experience.',
    'instructor.experience.richer': 'Professional barber specializing in precision cuts and contemporary styling.',
    'instructor.about.apo': 'Passionate educator and skilled barber dedicated to training the next generation of professionals.',
    'instructor.experience.apo': 'Experienced barber and instructor with expertise in advanced cutting techniques.',
    'instructor.about.bartosz': 'Creative stylist with a focus on modern trends and personalized client experiences.',
    'instructor.experience.bartosz': 'Skilled barber specializing in creative cuts and contemporary hair styling.',
    'instructor.about.ali': 'Dedicated professional with expertise in both traditional and modern barbering techniques.',
    'instructor.experience.ali': 'Experienced barber with a passion for delivering exceptional grooming services.',
    'instructor.about.tomasz': 'Experienced professional combining hands-on barbering skills with teaching excellence.',
    'instructor.experience.tomasz': 'Professional barber and educator committed to sharing knowledge and skills.',
    'testimonial.1.quote': 'The best place in Warsaw to quickly and above all well learn a profession from scratch. I have just finished the course, the guys helped with funding for the course and found me a job immediately after finishing. I highly recommend and thank you!',
    'testimonial.1.name': 'Angelika Ziółkowska',
    'testimonial.1.title': 'Graduate • 5-star Google Review',
    'testimonial.2.quote': 'I had the pleasure of taking part in a 3-day training course under the supervision of Tomek and Ali. I am delighted with the effects of the training. Great atmosphere and great educators. The boys gave us a huge dose of knowledge and tips on creating a portfolio. I highly recommend it!',
    'testimonial.2.name': 'Agata Antoniewicz',
    'testimonial.2.title': 'Graduate • 5-star Google Review',
    'testimonial.3.quote': 'Despite the time that has passed since the end of the course, I decided to leave a review. I participated in the month-long \'Barber from scratch\' course at K&K Academy, and I am very impressed with the level of professionalism and quality of the training. Educators Tomek, Bartek and Ali demonstrated not only theoretical knowledge, but also impressive practical skills. Now, 6 months after completing the course, I successfully run my own salon and I am glad that I had the opportunity to participate in the course from scratch with the guys.',
    'testimonial.3.name': 'Sharp Cut Barber',
    'testimonial.3.title': 'Salon Owner • 5-star Google Review',
    'common.graduate': 'Graduate',
    'common.review': 'Google Review',
    'common.star': 'star',
    'common.show.more': 'Show more',
    'common.show.less': 'Show less',
    'common.all': 'all',
    'common.dates': 'dates',
    'common.upcoming': 'Upcoming',
    'months.january': 'January',
    'months.february': 'February',
    'months.march': 'March',
    'months.april': 'April',
    'months.may': 'May',
    'months.june': 'June',
    'months.july': 'July',
    'months.august': 'August',
    'months.september': 'September',
    'months.october': 'October',
    'months.november': 'November',
    'months.december': 'December',
  },

  tr: {
    // Navigation
    'nav.home': 'Ana Sayfa',
    'nav.courses': 'Kurslar',
    'nav.gallery': 'Galeri',
    'nav.instructors': 'Eğitmenler',
    'nav.students': 'Öğrenciler',
    'nav.success': 'Başarı Hikayeleri',
    'nav.blog': 'Blog',
    'nav.contact': 'İletişim',
    'nav.enroll': 'Kayıt Ol',

    // Hero Section
    'hero.title': 'K&K Berber Akademisi',
    'hero.subtitle': 'Varşova\'nın Önde Gelen Eğitmenleriyle Berberlik Sanatında Ustalaşın',
    'hero.description': 'Profesyonel akademimize katılın ve tutkunuzu kârlı bir kariyere dönüştürün. Kapsamlı eğitim, uygulamalı deneyim ve kariyer desteği.',
    'hero.cta.primary': 'Kursa Kayıt Ol',
    'hero.cta.secondary': 'Galeriyi Görüntüle',
    'hero.stats.graduates': 'Mezun',
    'hero.stats.experience': 'Yıl Deneyim',
    'hero.stats.placement': 'İş Yerleştirme',
    'hero.stats.instructors': 'Usta Eğitmen',

    // Features
    'features.expert.title': 'Uzman Eğitmenler',
    'features.expert.description': 'Varşova\'nın en iyi usta berberlerinden öğrenin',
    'features.hands.title': 'Uygulamalı Eğitim',
    'features.hands.description': 'Pratik yaklaşımımızla gerçek deneyim kazanın',
    'features.career.title': 'Kariyer Desteği',
    'features.career.description': 'Mezuniyetten sonra iş bulma yardımı ve kariyer geliştirme',
    'features.modern.title': 'Modern Teknikler',
    'features.modern.description': 'Berberlik endüstrisindeki en son trendler ve teknikler',

    // About Section
    'about.title': 'Hakkımızda',
    'about.subtitle': 'Neden K&K Academy\'yi Seçmelisiniz',
    'about.description': 'Yıllarca deneyim ve eğitime olan tutkumuzla, Varşova\'nın önde gelen berber akademisiyiz.',

    // Courses
    'courses.title': 'Kurslarımız',
    'courses.subtitle': 'Beceri seviyeniz ve kariyer hedefleriniz için mükemmel kursu seçin',
    'courses.beginner': 'Başlangıç Kursu',
    'courses.advanced': 'İleri Düzey Kurs',
    'courses.master': 'Usta Kursu',
    'courses.specialty': 'Özel Kurslar',
    'courses.view.all': 'Tüm Kursları Görüntüle',
    'courses.enroll': 'Kayıt Ol',
    'courses.learn.more': 'Daha Fazla Bilgi',
    'courses.duration': 'Süre',
    'courses.level': 'Seviye',
    'courses.price': 'Fiyat',
    'courses.upcoming': 'Yaklaşan Tarihler',
    'courses.cta.title': 'Berber Kariyerinize Bugün Başlamaya Hazır mısınız?',
    'courses.cta.description': 'Kapsamlı eğitim programlarımızla hayatlarını dönüştüren yüzlerce başarılı mezuna katılın.',
    'courses.cta.button': 'Bir Günlük Ücretsiz Kursa Katılın',

    // Instructors
    'instructors.title': 'Eğitmenlerimiz',
    'instructors.subtitle': 'Usta Berberler',
    'instructors.description': 'Tüm eğitim yolculuğunuzda size rehberlik edecek deneyimli eğitmenlerimizle tanışın.',

    // Testimonials
    'testimonials.title': 'Öğrenci Başarı Hikayeleri',
    'testimonials.subtitle': 'Başarı Hikayeleri',
    'testimonials.description': 'Tutkularını kârlı kariyerlere ve başarılı işlere dönüştüren mezunlarımızdan dinleyin.',

    // Gallery
    'gallery.title': 'Galerimiz',
    'gallery.subtitle': 'Çalışmalarımızı görün',
    'gallery.description': 'Öğrencilerimizin ve eğitmenlerimizin muhteşem çalışmalarını keşfedin.',

    // Contact
    'contact.title': 'Bize Ulaşın',
    'contact.subtitle': 'Sorularınız mı var? Size yardımcı olmak için buradayız',
    'contact.name': 'Ad Soyad',
    'contact.email': 'E-posta',
    'contact.phone': 'Telefon',
    'contact.message': 'Mesaj',
    'contact.program': 'Program Seçin',
    'contact.submit': 'Mesaj Gönder',
    'contact.info.title': 'İletişim Bilgileri',
    'contact.info.address': 'Adres',
    'contact.info.phone': 'Telefon',
    'contact.info.email': 'E-posta',
    'contact.info.hours': 'Çalışma Saatleri',

    // Footer
    'footer.description': 'Varşova\'da kapsamlı kurslar ve eğitim sunan profesyonel berber akademisi.',
    'footer.quick.links': 'Hızlı Bağlantılar',
    'footer.contact.info': 'İletişim Bilgileri',
    'footer.follow': 'Bizi Takip Edin',
    'footer.rights': 'Tüm hakları saklıdır.',

    // Blog
    'blog.title': 'Blogumuz',
    'blog.subtitle': 'En son haberler ve ipuçları',
    'blog.read.more': 'Devamını Oku',
    'blog.view.all': 'Tüm Gönderileri Görüntüle',

    // CTA
    'cta.title': 'Kariyerinize Bugün Başlayın',
    'cta.description': 'Tutkularını kârlı bir kariyere dönüştüren binlerce başarılı mezuna katılın.',
    'cta.button': 'Şimdi Kayıt Olun',

    // Common
    'common.loading': 'Yükleniyor...',
    'common.error': 'Bir hata oluştu',
    'common.success': 'Başarılı!',
    'common.close': 'Kapat',
    'common.save': 'Kaydet',
    'common.cancel': 'İptal',
    'common.edit': 'Düzenle',
    'common.delete': 'Sil',
    'common.view': 'Görüntüle',
    'common.back': 'Geri',
    'common.next': 'İleri',
    'common.previous': 'Önceki',

    // Additional translations for missing components
    'our.vibe': 'Atmosferimiz!',
    'programs.fundamentals': 'Berber Temelleri',
    'programs.master': 'Usta Teknikleri',
    'programs.business': 'İş Ustalığı',
    'programs.private': 'Özel Dersler',
    'quicklinks.about': 'Hakkımızda',
    'quicklinks.admissions': 'Kabul',
    'quicklinks.financial': 'Mali Yardım',
    'quicklinks.portal': 'Öğrenci Portalı',
    'copyright': '© 2024 K&K Berber Akademisi. Tüm hakları saklıdır.',
    'policies.privacy': 'Gizlilik Politikası',
    'policies.terms': 'Hizmet Şartları',
    'policies.handbook': 'Öğrenci El Kitabı',
    'working.hours': 'Çalışma saatleri:',
    'blog.latest': 'En Son Görüşler',
    'blog.tips': 'Berberlik dünyasında en ön sırada kalmanızı sağlayacak ipuçları, trendler ve kaynaklar.',
    'upcoming.dates': 'Yaklaşan Tarihler',
    'show.all': 'Tümünü göster',
    'show.less': 'Daha az göster',
    'dates': 'tarihler',
    'testimonials.see.student.works': 'Tüm Öğrenci Çalışmalarını Gör',
    'testimonials.see.success.stories': 'Tüm Başarı Hikayeleri',
    'free.course': 'Ücretsiz Kurs',
    'not.sure': 'Henüz emin değilim',
    'senior.barber.instructor': 'Kıdemli Berber Eğitmeni',
    'send.inquiry': 'Sorgulama Gönder',
    'your.name': 'Adınız',
    'your.email': 'E-postanız',
    'select.program': 'Program seçin...',
    'program.interest': 'Program İlgi Alanı',
    
    // About Section Translation Keys  
    'about.features.certified': 'Endüstri tanınırlığı ile devlet sertifikalı programlar',
    'about.features.handson': 'Profesyonel düzeyde ekipmanla uygulamalı eğitim',
    'about.features.placement': 'Kariyer yerleştirme yardımı ve sürekli destek',
    'about.learn.more': 'Hakkımızda Daha Fazla Bilgi',
    'about.certified.excellence': 'Sertifikalı Mükemmellik',
    'about.state.licensed': 'Devlet Lisanslı Akademi',
    'common.free': 'ÜCRETSİZ',
    
    // Course Translation Keys
    'courses.enroll.now': 'Şimdi Kayıt Ol',
    'courses.cta.title': 'Berberlik Kariyerinizi Başlatmaya Hazır mısınız?',
    'courses.cta.description': 'Akademimize katılın ve sizi berberlik endüstrisinde öne çıkaracak becerilerde ustalaşın.',
    'courses.cta.button': 'Yolculuğunuza Başlayın',
    'course.duration.4hours': '4 saat',
    'course.duration.1month': '1 ay',
    'course.duration.3days': '3 gün',
    'course.duration.2weeks': '2 hafta',
    'course.certification.experience': 'Deneyim Sertifikası',
    'course.certification.professional': 'Profesyonel Sertifika',
    'course.certification.advanced': 'İleri Düzey Sertifika',
    'course.certification.specialist': 'Uzman Sertifikası',

    // Instructors Translation Keys
    'instructors.title': 'Eğitmenlerimizle Tanışın',
    'instructors.subtitle': 'Sektör Uzmanları',
    'instructors.description': 'Deneyimli berberlerimiz, Varşova\'nın en iyi salonlarında yıllarca deneyim sahibi uygulayıcılarıdır. En iyilerden öğrenin.',
    'senior.barber.instructor': 'Kıdemli Berber Eğitmeni',
    'instructor.richer.karimov': 'Richer Karimov',
    'instructor.apo.karimov': 'Apo Karimov',
    'instructor.bartosz.kaczorowski': 'Bartosz Kaczorowski',
    'instructor.ali.karimov': 'Ali Karimov',
    'instructor.tomasz.kaczorowski': 'Tomasz Kaczorowski',

    // Contact Translation Keys
    'contact.title': 'Yolculuğunuzu',
    'contact.title.highlight': 'Başlatın',
    'contact.title.today': 'Bugün',
    'contact.subtitle': 'Tutkunuzu profesyonel bir kariyere dönüştürmeye hazır mısınız? Programlarımız hakkında daha fazla bilgi edinmek ve kampüs turu planlamak için kabul ekibimizle iletişime geçin.',
    'contact.visit.campus': 'Kampüsümüzü Ziyaret Edin',
    'contact.call.us': 'Bizi Arayın',
    'contact.email.us': 'Bize E-posta Gönderin',
    'contact.hours': 'Saatler',
    'contact.hours.schedule': 'Pazartesi-Cuma: 12:00 - 21:00, Cumartesi: 12:00 - 17:00',
    'contact.form.title': 'Daha Fazla Bilgi Alın',
    'contact.form.first.name': 'Ad',
    'contact.form.last.name': 'Soyad',
    'contact.form.email': 'E-posta',
    'contact.form.phone': 'Telefon',
    'contact.form.program': 'Program İlgisi',
    'contact.form.message': 'Mesaj',
    'contact.form.submit': 'Sorgu Gönder',
    'contact.form.required': 'Lütfen gerekli alanları doldurun',
    'contact.form.required.desc': 'Ad, Soyad ve E-posta gereklidir.',
    'contact.form.thank.you': 'İlginiz için teşekkürler!',
    'contact.form.thank.you.desc': 'Daha fazla bilgi ile yakında sizinle iletişime geçeceğiz.',
    'contact.program.free': 'Ücretsiz Kurs',
    'contact.program.beginner': 'Başlangıç Kursu (1 ay)',
    'contact.program.advanced': 'İleri Kurs (3 gün)',
    'contact.program.specialist': 'Uzman Kursu (2 hafta)',
    'contact.program.select': 'Bir program seçin',

    // Gallery Translation Keys
    'gallery.view.full': 'Tam Galeriyi Görüntüle',

    // Blog Translation Keys
    'blog.latest': 'Son Haberler',
    'blog.tips': 'Profesyonellerimizden profesyonel ipuçları, sektör trendleri ve uzman görüşleri alın.',
    'blog.read.more': 'Devamını Oku',

    // CTA Enroll Translation Keys
    'cta.enroll.title': 'Berber Yolculuğunuzu Bugün Başlatın',
    'cta.enroll.description': 'Şimdi başvurun ve stilin geleceğini şekillendiren elit berberlerden oluşan topluluğumuza katılın.',
    'cta.enroll.button': 'Yolculuğunuza Başlayın',

    // Page Translation Keys
    'course.not.found': 'Kurs bulunamadı.',
    'page.gallery.title': 'Tam',
    'page.gallery.title.highlight': 'Galeri',
    'page.gallery.loading': 'Komplet çalışma koleksiyonumuzu keşfedin',
    'page.gallery.explore': '${count} profesyonel çalışma ve eğitim anımızdan oluşan komplet koleksiyonumuzu keşfedin',
    'page.students.title': 'Öğrenci',
    'page.students.title.highlight': 'Çalışmaları',
    'page.students.explore': 'Öğrencilerimizin harika dönüşümlerini ve becerilerini görün',
    'page.success.title': 'Başarı',
    'page.success.title.highlight': 'Hikayeleri',
    'page.success.explore': 'Mezunlarımızın ilham verici hikayelerini keşfedin',
    'page.back.home': 'Ana Sayfaya Dön',
    'page.apply.now': 'Şimdi Başvur',
    'page.showcased.works': 'sergilenen çalışma',
    'page.blog.title': 'Akademi',
    'page.blog.title.highlight': 'Görüşleri',
    'page.blog.subtitle': 'Modern berberlik dünyasından haberler, ipuçları ve trendler.',

    // Blog Post Translation Keys
    'blog.post.career.title': 'Berberlikte Kariyer Nasıl Başlatılır',
    'blog.post.career.excerpt': 'Berber olmayı mı düşünüyorsunuz? İlk 30 gününüz böyle görünebilir...',
    'blog.post.fade.title': '2025 için En İyi 5 Fade Tekniği',
    'blog.post.fade.excerpt': 'Her müşterinin soracağı bu mutlaka bilinmesi gereken fade varyasyonları ile önde kalın.',
    'blog.post.toolkit.title': 'Berber Araç Seti: Gerekli vs. Güzel Olur',
    'blog.post.toolkit.excerpt': 'Makinelerden tarağa kadar, fazla harcama yapmadan profesyonel kit oluşturma rehberimiz.',
    'blog.tag.beginner': 'Başlangıç',
    'blog.tag.trends': 'Trendler',
    'blog.tag.tools': 'Araçlar',
    'blog.filter.all': 'Tümü',

    // Contact Page Translation Keys
    'contact.title': 'Bizimle',
    'contact.title.highlight': 'iletişime',
    'contact.title.today': 'geçin',
    'contact.subtitle': 'Berberlik yolculuğunuza başlamaya hazır mısınız? Kabul ekibimiz her adımda size yardımcı olmak için burada.',
    'contact.visit.campus': 'Kampüsümüzü ziyaret edin',
    'contact.call.us': 'Bizi arayın',
    'contact.email.us': 'E-posta gönderin',
    'contact.hours': 'Çalışma saatleri',
    'contact.hours.weekdays': 'Pzt-Cum: 12:00 - 21:00',
    'contact.hours.saturday': 'Cmt: 12:00 – 17:00',
    'contact.hours.sunday': 'Paz: Kapalı',
    'contact.form.first.name': 'Ad',
    'contact.form.last.name': 'Soyad',
    'contact.form.email': 'E-posta',
    'contact.form.phone': 'Telefon',
    'contact.form.program': 'Program',
    'contact.form.program.placeholder': 'Bir program seçin...',
    'contact.form.program.basic': 'Temel Berber Kursu',
    'contact.form.program.advanced': 'İleri Teknikler',
    'contact.form.program.complete': 'Tam Program',
    'contact.form.program.free': 'Ücretsiz Kurs',
    'contact.form.message': 'Mesaj',
    'contact.form.message.placeholder': 'Hedefleriniz ve deneyiminiz hakkında bize anlatın...',
    'contact.form.title': 'Bize mesaj gönderin',
    'contact.form.submit': 'Mesaj Gönder',
    'contact.form.required': 'Gerekli alanlar',
    'contact.form.required.desc': 'Lütfen tüm gerekli alanları doldurun.',
    'contact.form.thank.you': 'Teşekkürler!',
    'contact.form.thank.you.desc': 'Mesajınız gönderildi. Yakında sizinle iletişime geçeceğiz.',
    'contact.page.title': 'İletişim',
    'contact.page.highlight': 'K&K Academy',
    'contact.page.subtitle': 'Programlarımız, fiyatlar veya kayıt hakkında sorularınız mı var? Bizimle iletişime geçin, kabul ekibimiz memnuniyetle yardımcı olacaktır.',
    'contact.form.error': 'Mesaj gönderme hatası',
    'contact.form.error.desc': 'Lütfen daha sonra tekrar deneyin.',
    'contact.form.success': 'Mesaj gönderildi!',
    'contact.form.success.desc': 'Yakında sizinle iletişime geçeceğiz.',

    // Course Details Translation Keys
    'course.not.found': 'Kurs bulunamadı',
    'course.overview': 'Kurs Genel Bakış',
    'course.curriculum': 'Müfredat',
    'course.instructors': 'Eğitmenler',
    'course.gallery': 'Galeri',
    'course.book.now': 'Şimdi Rezervasyon Yap',
    'course.duration': 'Süre',
    'course.students': 'Öğrenciler',
    'course.certification': 'Sertifikasyon',
    'course.what.learn': 'Neler öğreneceksiniz',
    'course.upcoming.dates': 'Yaklaşan Tarihler',
    'course.enroll.today': 'Bugün Kayıt Ol',
    'course.meet.instructors': 'Eğitmenlerinizle Tanışın',
    'course.select.date': 'Tercih ettiğiniz başlangıç tarihini seçin',
    'course.audience': 'Bu Kurs Kimler İçin',
    'course.how.works': 'Kurs Nasıl Çalışır',
    'course.whats.included': 'Neler Dahil',
    'course.outcomes': 'Sonunda şunları yapabileceksiniz…',
    'course.gallery.title': 'Kursta Neler Oluyor',
    'course.gallery.subtitle': 'Uygulamalı eğitimimizden anlık görüntüleri inceleyin.',
    'course.certificate.title': 'Sertifika ve Akreditasyon',
    'course.certificate.description': 'Tamamladığınızda, berberllik için tanınmış bir eğitim kurumu olan K&K Academy tarafından verilmiş sertifika alacaksınız.',
    'course.certificate.accredited': 'Akredite Sertifika',
    'course.certificate.industry': 'Sektörde Tanınan',
    'course.certificate.portfolio': 'Çalışma Portföyü',
    'course.pricing.title': 'Fiyatlandırma ve Planlar',
    'course.pricing.description': 'İhtiyaçlarınıza ve bütçenize en uygun planı seçin.',
    'course.pricing.full.payment': 'Tam Ödeme',
    'course.pricing.installments': 'Taksitli Ödeme',
    'course.pricing.contact': 'Detaylar İçin İletişime Geçin',
    'course.faq.title': 'Sık Sorulan Sorular',
    'course.faq.experience.q': 'Önceden deneyimim olması gerekli mi?',
    'course.faq.experience.a': 'Hayır, başlangıç kurslarımız berberlik deneyimi olmayan kişiler için tasarlanmıştır.',
    'course.faq.tools.q': 'Kendi araçlarımı satın almam gerekir mi?',
    'course.faq.tools.a': 'Hayır, kurs süresince tüm araçlar ve malzemeler sağlanır. Ayrıca satın almanız önerilen araçların listesini de alacaksınız.',
    'course.faq.job.q': 'İş bulma konusunda yardım ediyor musunuz?',
    'course.faq.job.a': 'Evet, iş bulma desteği sunuyoruz ve yerel berber dükkanları ile ortaklığımız bulunmaktadır.',
    'course.cta.final.title': 'Yolculuğunuza Bugün Başlayın',
    'course.cta.final.description': 'Berberlikte başarılı kariyerler inşa etmiş yüzlerce memnun mezunumuza katılın.',
    'course.cta.final.button': 'Şimdi Kayıt Ol',

    // Beginner Course (ID: 1) Specific Translations
    'course.beginner.skills.0': 'Klasik ve modern saç kesimi',
    'course.beginner.skills.1': 'Makine soluklaması (alçak/orta/yüksek)',
    'course.beginner.skills.2': 'Ustura işi ve detaylar',
    'course.beginner.skills.3': 'Sakal şekillendirme ve bakım',
    
    'course.beginner.audience.0': 'Deneyimi olmayan kişiler',
    'course.beginner.audience.1': 'Kariyer değiştirenler',
    'course.beginner.audience.2': 'Okul sonrası öğrenciler',
    
    'course.beginner.howItWorks.0': 'Teori',
    'course.beginner.howItWorks.1': 'Manken Üzerinde Pratik',
    'course.beginner.howItWorks.2': 'Gerçek Müşteriler',
    'course.beginner.howItWorks.0.desc': 'Etkileşimli dersler ve gösteriler',
    'course.beginner.howItWorks.1.desc': 'Kas hafızasını güvenle geliştir',
    'course.beginner.howItWorks.2.desc': 'Canlı modeller üzerinde denetimli kesim',
    
    'course.beginner.includes.0': 'Profesyonel makas ve tarak hediyesi',
    'course.beginner.includes.1': 'Tüm araçlar sağlanır',
    'course.beginner.includes.2': 'Tamamlama sertifikası',
    
    'course.beginner.outcomes.0': 'Modern kesim ve soluklamalar yap',
    'course.beginner.outcomes.1': 'Güvenle sakal stilize et',
    'course.beginner.outcomes.2': 'Berber kariyeri başlat',

    // Instructor Details Translation Keys
    'instructor.not.found': 'Eğitmen bulunamadı',
    'instructor.apply.now': 'Şimdi Başvur',
    'instructor.experience': 'Deneyim',
    'instructor.specializations': 'Uzmanlık Alanları',
    'instructor.about': 'Eğitmen Hakkında',
    'instructor.contact': 'İletişim',
    'senior.barber.instructor': 'Kıdemli Berber Eğitmeni',

    // About Section CTA
    'about.cta': 'Yolculuğunuza Başlayın',

    // Individual Instructor Details
    'instructor.1.about': 'Klasik berberlik tekniklerinde uzman, 10+ yıl deneyim. Hassas kesimler ve sakal şekillendirmede uzmanlaşmış.',
    'instructor.1.experience': 'Deneyim: 12+ yıl',
    'instructor.2.about': 'Modern trendlerin ve yaratıcı stillerin ustası. İleri seviye öğrenciler için atölyeler yönetir.',
    'instructor.2.experience': 'Deneyim: 8+ yıl',
    'instructor.3.about': 'Geleneksel teknikler ve hassas tıraş uzmanı. Yeni eğitmenlere mentorluk yapar.',
    'instructor.3.experience': 'Deneyim: 15+ yıl',
    'instructor.4.about': 'Modern kesim teknikleri ve renklendirme uzmanı. Sertifikalı uluslararası eğitmen.',
    'instructor.4.experience': 'Deneyim: 10+ yıl',
    'instructor.5.about': 'Klasik berberlik ve şekillendirme ustası. İleri seviye kurslar yönetir.',
    'instructor.5.experience': 'Deneyim: 14+ yıl',

    'course.free.title': 'Bir Günlük Ücretsiz Berberlik Kursu',
    'course.free.subtitle': 'Berberlik Dünyasının Gerçek Tadını Alın – Ücretsiz',
    'course.free.description': 'Berber olmak hakkında merak ediyor ama nereden başlayacağınızı bilmiyor musunuz? Bir Günlük Ücretsiz Kursumuz, profesyonel bir berberlik akademisinin parçası olmanın gerçekte nasıl bir şey olduğunu deneyimlemenin mükemmel yolu.',
    'course.free.badge': 'Ücretsiz Kurs',
    'course.beginner.title': 'Başlangıç Berber Kursu – Sıfırdan Berbere',
    'course.beginner.subtitle': 'Tam hazırlık ve güvenle yeni bir mesleğe başlayın',
    'course.beginner.description': 'Teori, manken pratiği ve canlı modeller üzerinde günlük çalışma ile mutlak başlangıç seviyesindeki kişileri profesyonel berberlere dönüştüren yoğun 24 günlük program (Pzt-Cmt, 12-20).',
    'course.beginner.badge': 'Başlangıç',
    'course.advanced.title': 'Berberler İçin İleri Düzey Kurs',
    'course.advanced.subtitle': 'Becerilerinizi genişletin ve en son teknikleri öğrenin',
    'course.advanced.description': 'Aktif berberler (min 2 yıl) için modern kesimler, ileri düzey soluklar ve premium sakal işine odaklanan 3 günlük bootcamp (Pzt-Cmt, 12-20).',
    'course.advanced.badge': 'İleri Düzey',
    'course.specialist.title': 'Uzman Kurs – Trendler ve Yeni Teknikler',
    'course.specialist.subtitle': 'Becerilerinizi tazeleyin ve küresel trendlerde ustalaşın',
    'course.specialist.description': 'Kesim, soluk ve sakal stillemede en son küresel trendleri benimser berber/kuaförler için 2 haftalık program (Pzt-Cmt, 12-19).',
    'course.specialist.badge': 'Uzman',
    'instructor.about.richer': 'Yıllarca profesyonel deneyimle modern kesim teknikleri ve klasik berberlik stillerinde uzman.',
    'instructor.experience.richer': 'Hassas kesimler ve çağdaş stillemede uzmanlaşmış profesyonel berber.',
    'instructor.about.apo': 'Yeni nesil profesyonelleri yetiştirmeye adanmış tutkulu eğitimci ve yetenekli berber.',
    'instructor.experience.apo': 'İleri düzey kesim tekniklerinde uzmanlığa sahip deneyimli berber ve eğitmen.',
    'instructor.about.bartosz': 'Modern trendlere ve kişiselleştirilmiş müşteri deneyimlerine odaklanan yaratıcı stilist.',
    'instructor.experience.bartosz': 'Yaratıcı kesimler ve çağdaş saç stillemede uzmanlaşmış yetenekli berber.',
    'instructor.about.ali': 'Hem geleneksel hem de modern berberlik tekniklerinde uzmanlığa sahip adanmış profesyonel.',
    'instructor.experience.ali': 'Olağanüstü bakım hizmetleri sunma tutkusu olan deneyimli berber.',
    'instructor.about.tomasz': 'Uygulamalı berberlik becerilerini öğretim mükemmelliği ile birleştiren deneyimli profesyonel.',
    'instructor.experience.tomasz': 'Bilgi ve becerilerini paylaşma konusunda kararlı profesyonel berber ve eğitimci.',
    'testimonial.1.quote': 'Varşova\'da sıfırdan bir mesleği hızlı ve her şeyden önce iyi öğrenmek için en iyi yer. Kursu yeni bitirdim, çocuklar kurs finansmanında yardım ettiler ve bitirdikten hemen sonra bana iş buldular. Çok tavsiye ederim ve teşekkür ederim!',
    'testimonial.1.name': 'Angelika Ziółkowska',
    'testimonial.1.title': 'Mezun • 5 yıldızlı Google İncelemesi',
    'testimonial.2.quote': 'Tomek ve Ali\'nin gözetiminde 3 günlük eğitim kursuna katılma zevkini yaşadım. Eğitimin etkilerinden çok memnunum. Harika atmosfer ve harika eğitimciler. Çocuklar bize büyük bir bilgi dozu ve portföy oluşturma konusunda ipuçları verdi. Çok tavsiye ederim!',
    'testimonial.2.name': 'Agata Antoniewicz',
    'testimonial.2.title': 'Mezun • 5 yıldızlı Google İncelemesi',
    'testimonial.3.quote': 'Kursun bitiminden bu yana geçen zamana rağmen, bir inceleme yazmaya karar verdim. K&K Academy\'de aylık \'Sıfırdan Berber\' kursuna katıldım ve eğitimin profesyonellik düzeyi ve kalitesinden çok etkilendim. Eğitimciler Tomek, Bartek ve Ali sadece teorik bilgi değil, aynı zamanda etkileyici pratik beceriler de sergilediler. Şimdi, kursu bitirdikten 6 ay sonra, kendi salonumu başarıyla işletiyorum ve çocuklarla sıfırdan kursa katılma fırsatım olduğu için memnunum.',
    'testimonial.3.name': 'Sharp Cut Barber',
    'testimonial.3.title': 'Salon Sahibi • 5 yıldızlı Google İncelemesi',
    'common.graduate': 'Mezun',
    'common.review': 'Google İncelemesi',
    'common.star': 'yıldızlı',
    'common.show.more': 'Daha fazla göster',
    'common.show.less': 'Daha az göster',
    'common.all': 'tümü',
    'common.dates': 'tarihler',
    'common.upcoming': 'Yaklaşan',
    'months.january': 'Ocak',
    'months.february': 'Şubat',
    'months.march': 'Mart',
    'months.april': 'Nisan',
    'months.may': 'Mayıs',
    'months.june': 'Haziran',
    'months.july': 'Temmuz',
    'months.august': 'Ağustos',
    'months.september': 'Eylül',
    'months.october': 'Ekim',
    'months.november': 'Kasım',
    'months.december': 'Aralık',
  },
};